server:
  port: 8003
spring:
  application:
    name: its-shop-auth
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 123456
#    tomcat:
#      max-active: 30
#      max-wait: 10000
#      test-on-borrow: true
#      validation-interval: 30000
#      validation-query: SELECT 1
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    url: jdbc:mysql://192.168.118.131:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka