logging:
  config: classpath:logback.xml
server:
  port: 8701
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8002/xxl-job-admin
    executor:
      appname: xxl-job-executor
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9998
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: xxl-job-serivce
